import { useCallback, useEffect, useRef, useState } from 'react'
import { Navigate, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { CATEGORIES, inr } from '../types'
import { applyTheme, DEFAULT_THEME, SERIF, SANS, waLink } from '../lib/cms'
const STATUSES=['pending','confirmed','processing','packed','shipped','out_for_delivery','delivered','cancelled'],LABELS=['Front','Back','Side','Detail','Lifestyle','Fabric']
const box="w-full bg-transparent border-b border-sage py-2 text-sm"
async function isAdmin(){const {data:{user}}=await supabase.auth.getUser();if(!user)return false
  const {data}=await supabase.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();return !!data}
export function AdminLogin(){const nv=useNavigate();const [err,setErr]=useState('')
  const go=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget)
    const {error}=await supabase.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))})
    if(error)return setErr('Email or password is incorrect.');if(!(await isAdmin())){await supabase.auth.signOut();return setErr('This account does not have admin access.')};nv('/admin')}
  return <form onSubmit={go} className="min-h-screen grid place-items-center bg-forest text-ivory px-5"><div className="w-full max-w-sm space-y-6"><h1 className="font-serif text-5xl tracking-[.3em]">VELORA</h1><p className="text-soft">Admin sign in</p>
    <input name="email" type="email" required placeholder="Email" aria-label="Email" className={`${box} placeholder:text-sage`}/><input name="password" type="password" required placeholder="Password" aria-label="Password" className={`${box} placeholder:text-sage`}/>
    {err&&<p role="alert" className="text-soft">{err}</p>}<button className="btn bg-ivory text-forest border-ivory w-full">Sign in</button></div></form>}
export default function Admin(){const nv=useNavigate();const [ok,setOk]=useState<boolean|null>(null);const [tab,setTab]=useState('Dashboard')
  useEffect(()=>{isAdmin().then(setOk)},[]);if(ok===null)return <p className="p-20 text-center">Loading…</p>;if(!ok)return <Navigate to="/admin/login" replace/>
  return <div className="min-h-screen md:flex"><aside className="bg-forest text-ivory md:w-56 p-6 flex md:flex-col gap-4 overflow-x-auto"><p className="font-serif text-2xl tracking-[.3em] mr-4">VELORA</p>
    {TABS.map(t=><button key={t} onClick={()=>setTab(t)} className={`text-left text-sm ${tab===t?'text-ivory underline underline-offset-8':'text-soft'}`}>{t}</button>)}
    <button className="text-left text-sm text-sage md:mt-auto" onClick={async()=>{await supabase.auth.signOut();nv('/admin/login')}}>Sign out</button></aside>
    <main className="flex-1 p-6 md:p-10 min-w-0">{Panel(tab)}</main></div>}
function Dash(){const [d,set]=useState<any>(null)
  useEffect(()=>{(async()=>{const [o,p,c]=await Promise.all([supabase.from('orders').select('*').order('created_at',{ascending:false}),supabase.from('products').select('id,name,stock,sold').order('sold',{ascending:false}),supabase.from('customers').select('*').order('created_at',{ascending:false}).limit(5)])
    set({o:o.data||[],p:p.data||[],c:c.data||[]})})()},[]);if(!d)return <p>Loading…</p>
  const live=d.o.filter((x:any)=>x.status!=='cancelled'),sales=live.reduce((s:number,x:any)=>s+Number(x.total),0)
  const days=[...Array(7)].map((_,i)=>{const t=new Date(Date.now()-(6-i)*864e5).toDateString();return {l:t.slice(4,10),v:live.filter((x:any)=>new Date(x.created_at).toDateString()===t).reduce((s:number,x:any)=>s+Number(x.total),0)}}),mx=Math.max(1,...days.map(x=>x.v))
  const stat=[['Total sales',inr(sales)],['Total orders',d.o.length],['Pending',d.o.filter((x:any)=>x.status==='pending').length],['Delivered',d.o.filter((x:any)=>x.status==='delivered').length]]
  return <div className="space-y-12"><div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{stat.map(([l,v])=><div key={l as string} className="bg-soft/40 p-6"><p className="text-xs text-olive">{l}</p><p className="font-serif text-4xl mt-2">{v}</p></div>)}</div>
    <section><h2 className="font-serif text-3xl mb-4">Revenue, last 7 days</h2><div className="flex items-end gap-3 h-40">{days.map(x=><div key={x.l} className="flex-1 flex flex-col justify-end items-center gap-1 h-full"><div className="w-full bg-olive" style={{height:`${x.v/mx*100}%`}} title={inr(x.v)}/><span className="text-[10px]">{x.l}</span></div>)}</div></section>
    <div className="grid lg:grid-cols-2 gap-10"><List t="New orders" r={d.o.slice(0,5).map((x:any)=>`${x.order_number} · ${x.customer_name} · ${inr(x.total)}`)}/><List t="Low stock" r={d.p.filter((x:any)=>x.stock<=5).map((x:any)=>`${x.name} · ${x.stock} left`)}/>
      <List t="Best sellers" r={d.p.filter((x:any)=>x.sold>0).slice(0,5).map((x:any)=>`${x.name} · ${x.sold} sold`)}/><List t="Recent customers" r={d.c.map((x:any)=>x.full_name||'Customer')}/></div></div>}
const List=({t,r}:{t:string;r:string[]})=><section><h2 className="font-serif text-3xl mb-3">{t}</h2>{r.length?r.map((x,i)=><p key={i} className="py-2 border-b border-soft text-sm">{x}</p>):<p className="text-sm text-olive">Nothing here yet.</p>}</section>
function Orders(){const [o,set]=useState<any[]>([]);const load=useCallback(()=>{supabase.from('orders').select('*').order('created_at',{ascending:false}).then(({data})=>set(data||[]))},[]);useEffect(load,[load])
  const save=async(x:any,e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.from('orders').update({status:f.get('status'),tracking_number:f.get('tracking'),courier:f.get('courier'),payment_status:f.get('pay'),updated_at:new Date().toISOString()}).eq('id',x.id);alert(error?'Could not save. Try again.':'Order updated.');load()}
  return <div><h1 className="font-serif text-5xl mb-8">Orders</h1>{!o.length&&<p className="text-olive">No orders yet.</p>}{o.map(x=><form key={x.id} onSubmit={e=>save(x,e)} className="border-b border-soft py-6 grid lg:grid-cols-[2fr_3fr] gap-6">
    <div className="text-sm"><p className="font-medium">{x.order_number} · {inr(x.total)}</p><p>{x.customer_name} · {x.customer_phone}</p><p className="text-olive">{x.shipping_address}</p><p>{(x.items||[]).map((i:any)=>`${i.name} (${i.size}) ×${i.qty}`).join(', ')}</p><p className="text-sage">{new Date(x.created_at).toLocaleString()}</p>{x.customer_phone&&<a href={waLink(x.customer_phone,`Hello ${x.customer_name}, your VELORA order ${x.order_number} is ${x.status.replace(/_/g,' ')}.`)} target="_blank" rel="noreferrer" className="underline">Message customer on WhatsApp</a>}</div>
    <div className="grid grid-cols-2 gap-3 items-end"><select name="status" defaultValue={x.status} className={box}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select><select name="pay" defaultValue={x.payment_status} className={box}><option>unpaid</option><option>paid</option><option>refunded</option></select>
      <input name="tracking" defaultValue={x.tracking_number||''} placeholder="Tracking number" className={box}/><input name="courier" defaultValue={x.courier||''} placeholder="Courier" className={box}/><button className="btn btn-dark col-span-2">Save</button></div></form>)}</div>}
function Products(){const [p,set]=useState<any[]>([]);const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);const load=useCallback(()=>{supabase.from('products').select('*').order('created_at',{ascending:false}).then(({data})=>set(data||[]))},[]);useEffect(load,[load])
  const up=async(bucket:string,path:string,file:File)=>{const {error}=await supabase.storage.from(bucket).upload(path,file,{upsert:true});if(error)throw error;return supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl}
  const add=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),files=LABELS.map((_,i)=>f.get('img'+i) as File).map(x=>x&&x.size?x:null)
    if(files.filter(Boolean).length<4)return setMsg('Upload at least 4 of the 6 images.');if(files.some(x=>x&&!x.type.startsWith('image/')))return setMsg('Images only, please.')
    setBusy(true);setMsg('Uploading…');try{const id=crypto.randomUUID();const v=f.get('video') as File
      const {error}=await supabase.from('products').insert({id,name:f.get('name'),slug:f.get('slug'),price:Number(f.get('price')),discount_price:f.get('disc')?Number(f.get('disc')):null,category:f.get('cat'),collection:f.get('collection'),sku:f.get('sku'),stock:Number(f.get('stock')),
        sizes:String(f.get('sizes')).split(',').map(s=>s.trim()).filter(Boolean),color:f.get('color'),colors:[String(f.get('color'))],description:f.get('desc'),is_featured:f.get('feat')==='on',is_new:f.get('new')==='on',published:false});if(error)throw error
      const rows=[];for(let i=0;i<6;i++){const fl=files[i];if(fl)rows.push({product_id:id,position:i+1,label:LABELS[i],url:await up('product-images',`${id}/${i+1}.${fl.name.split('.').pop()}`,fl)})}
      const r=await supabase.from('product_images').insert(rows);if(r.error)throw r.error
      const patch:any={published:true,image_url:rows[0].url};if(v&&v.size){patch.video_url=await up('product-videos',`${id}/video.mp4`,v)}
      const u=await supabase.from('products').update(patch).eq('id',id);if(u.error)throw u.error;form.reset();setMsg('Product published.');load()}catch(x:any){setMsg('Could not save: '+(x.message||'unknown error'))}setBusy(false)}
  const del=async(id:string)=>{if(confirm('Delete this product?')){await supabase.from('products').delete().eq('id',id);load()}}
  return <div><h1 className="font-serif text-5xl mb-8">Products</h1><form onSubmit={add} className="grid md:grid-cols-3 gap-x-6 gap-y-4 max-w-4xl">
    <input name="name" required placeholder="Product name" className={box}/><input name="slug" required pattern="[a-z0-9-]+" placeholder="slug-like-this" className={box}/><input name="sku" placeholder="SKU" className={box}/>
    <input name="price" type="number" required min="0" placeholder="Price" className={box}/><input name="disc" type="number" min="0" placeholder="Discount price" className={box}/><input name="stock" type="number" required min="0" placeholder="Stock" className={box}/>
    <select name="cat" className={box}>{CATEGORIES.map(c=><option key={c} value={c}>{c}</option>)}</select><input name="collection" placeholder="Collection" className={box}/><input name="color" required placeholder="Color" className={box}/>
    <input name="sizes" defaultValue="S,M,L,XL" placeholder="Sizes, comma separated" className={`${box} md:col-span-2`}/><label className="text-sm flex gap-4"><span><input type="checkbox" name="feat"/> Featured</span><span><input type="checkbox" name="new"/> New arrival</span></label>
    <textarea name="desc" placeholder="Description" className={`${box} md:col-span-3`}/>
    {LABELS.map((l,i)=><label key={l} className="text-xs text-olive">{i+1}. {l}<input type="file" name={'img'+i} accept="image/*" className="block mt-1"/></label>)}<label className="text-xs text-olive">Video (MP4)<input type="file" name="video" accept="video/mp4" className="block mt-1"/></label>
    <button disabled={busy} className="btn btn-dark md:col-span-3">{busy?'Saving…':'Publish product'}</button>{msg&&<p role="status" className="md:col-span-3 text-sm">{msg}</p>}</form>
    <div className="mt-12">{p.map(x=><details key={x.id} className="border-b border-soft py-3"><summary className="cursor-pointer text-sm">{x.name} · {x.category} · {inr(x.price)} · {x.stock} in stock {x.published?'':'(draft)'}</summary><ProductEdit x={x} done={load}/><button onClick={()=>del(x.id)} className="underline text-sm mt-4">Delete product</button></details>)}</div></div>}
const upload=async(bucket:string,path:string,file:File)=>{const {error}=await supabase.storage.from(bucket).upload(path,file,{upsert:true});if(error)throw error;return supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl+'?v='+Date.now()}
const okLink=(l:string)=>!l||l.startsWith('/')||/^https:\/\//.test(l)
function HeroAdmin(){const [s,set]=useState<any[]>([]);const load=useCallback(()=>{supabase.from('hero_slides').select('*').order('position').then(({data})=>set(data||[]))},[]);useEffect(load,[load])
  const move=async(k:number,d:number)=>{const a=s[k],b=s[k+d];if(!b)return;await supabase.from('hero_slides').upsert([{...a,position:b.position},{...b,position:a.position}].map(x=>({...x})));load()}
  const del=async(id:string)=>{if(confirm('Delete this slide?')){await supabase.from('hero_slides').delete().eq('id',id);load()}}
  return <div><h1 className="font-serif text-5xl mb-2">Hero slides</h1><p className="text-sm text-olive mb-8">Slides show on the homepage in this order. With one slide there is no carousel; with none, a default hero is shown.</p>
    {s.map((x,k)=><details key={x.id} className="border-b border-soft py-4"><summary className="cursor-pointer flex justify-between"><span>{k+1}. {x.headline||'Untitled slide'} {x.active?'':'(hidden)'}</span></summary>
      <div className="flex gap-4 my-3 text-xs"><button onClick={()=>move(k,-1)} disabled={!k}>Move up</button><button onClick={()=>move(k,1)} disabled={k===s.length-1}>Move down</button><button onClick={()=>del(x.id)} className="underline">Delete</button></div><SlideForm x={x} pos={k} done={load}/></details>)}
    <h2 className="font-serif text-3xl mt-10 mb-4">Add a slide</h2><SlideForm key={s.length} pos={s.length} done={load}/></div>}
function SlideForm({x,pos,done}:{x?:any;pos:number;done:()=>void}){const [busy,setBusy]=useState(false);const [op,setOp]=useState<number>(x?.overlay_opacity??.4);const [msg,setMsg]=useState('')
  const go=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const l1=String(f.get('l1')),l2=String(f.get('l2'))
    if(!okLink(l1)||!okLink(l2))return setMsg('Links must start with / or https://');setBusy(true)
    try{const id=x?.id||crypto.randomUUID(),im=f.get('img') as File,vd=f.get('vid') as File
      const row:any={id,position:x?.position??pos,headline:f.get('h'),subheading:f.get('s'),cta_text:f.get('c1'),cta_link:l1,cta2_text:f.get('c2'),cta2_link:l2,overlay_opacity:op,overlay_tone:f.get('tone'),autoplay:f.get('auto')==='on',loop:f.get('loop')==='on',active:f.get('act')==='on',image_url:x?.image_url??null,video_url:x?.video_url??null}
      if(im?.size){if(!im.type.startsWith('image/'))throw new Error('Choose an image file.');row.image_url=await upload('hero-media',`${id}/image.${im.name.split('.').pop()}`,im)}
      if(vd?.size){if(vd.type!=='video/mp4')throw new Error('Video must be an MP4.');row.video_url=await upload('hero-media',`${id}/video.mp4`,vd)}
      const {error}=await supabase.from('hero_slides').upsert(row);if(error)throw error;setMsg('Saved.');done()}catch(er:any){setMsg('Could not save: '+er.message)}setBusy(false)}
  const b=(n:string,l:string,v?:string)=><input name={n} defaultValue={v||''} placeholder={l} aria-label={l} className={box}/>
  return <form onSubmit={go} className="grid md:grid-cols-2 gap-x-6 gap-y-4 max-w-3xl">{b('h','Headline',x?.headline)}{b('s','Subheading',x?.subheading)}{b('c1','Button 1 text',x?.cta_text)}{b('l1','Button 1 link (/shop)',x?.cta_link)}{b('c2','Button 2 text',x?.cta2_text)}{b('l2','Button 2 link',x?.cta2_link)}
    <label className="text-xs text-olive">Image{x?.image_url&&' (replace)'}<input type="file" name="img" accept="image/*" className="block mt-1"/></label><label className="text-xs text-olive">Video MP4 — replaces the image{x?.video_url&&' (replace)'}<input type="file" name="vid" accept="video/mp4" className="block mt-1"/></label>
    <label className="text-xs text-olive">Overlay strength {Math.round(op*100)}%<input type="range" min="0" max="0.9" step="0.05" value={op} onChange={e=>setOp(Number(e.target.value))} className="block w-full"/></label>
    <select name="tone" defaultValue={x?.overlay_tone||'dark'} className={box} aria-label="Overlay"><option value="dark">Dark overlay, light text</option><option value="light">Light overlay, dark text</option></select>
    <div className="md:col-span-2 flex flex-wrap gap-6 text-sm">{[['auto','Autoplay',x?.autoplay??true],['loop','Loop video',x?.loop??true],['act','Visible',x?.active??true]].map(([n,l,d])=><label key={n as string}><input type="checkbox" name={n as string} defaultChecked={d as boolean}/> {l}</label>)}</div>
    <button disabled={busy} className="btn btn-dark md:col-span-2">{busy?'Saving…':x?'Save slide':'Add slide'}</button>{msg&&<p role="status" className="md:col-span-2 text-sm">{msg}</p>}</form>}
function ThemeAdmin(){const [t,set]=useState<any>(null);const [msg,setMsg]=useState('')
  useEffect(()=>{supabase.from('theme_settings').select('value').eq('key','theme').maybeSingle().then(({data})=>set(data?.value||DEFAULT_THEME))},[]);if(!t)return <p>Loading…</p>
  const ch=(k:string,v:any)=>{const n={...t,[k]:v};set(n);applyTheme(n)}
  const save=async()=>{const {error}=await supabase.from('theme_settings').upsert({key:'theme',value:t});setMsg(error?'Could not save. Try again.':'Theme saved. It is live on the storefront.')}
  return <div className="max-w-xl"><h1 className="font-serif text-5xl mb-2">Theme</h1><p className="text-sm text-olive mb-8">Changes preview instantly here. Save to publish them.</p>
    {[['primary','Primary (header, footer, buttons)'],['secondary','Secondary'],['accent','Accent'],['soft','Soft background'],['background','Page background']].map(([k,l])=><label key={k} className="flex justify-between items-center py-3 border-b border-soft text-sm">{l}<input type="color" value={t[k]||'#000000'} onChange={e=>ch(k,e.target.value)} aria-label={l}/></label>)}
    <label className="block py-4 text-sm">Corner radius {t.radius||0}px<input type="range" min="0" max="24" value={t.radius||0} onChange={e=>ch('radius',Number(e.target.value))} className="block w-full mt-2"/></label>
    {[['logo_url','Logo'],['favicon_url','Favicon']].map(([k,l])=><label key={k} className="block py-3 text-sm border-b border-soft">{l}{t[k]&&<img src={t[k]} alt="" className="h-10 my-2"/>}<input type="file" accept="image/*" className="block mt-1 text-xs" onChange={async e=>{const fl=e.target.files?.[0];if(fl)try{ch(k,await upload('campaign-media',`brand/${k}-${Date.now()}`,fl))}catch{setMsg('Upload failed.')}}}/></label>)}
    {[['fontSerif','Heading font',SERIF],['fontSans','Body font',SANS],['buttonStyle','Buttons',['outline','solid']],['headerStyle','Header',['transparent','solid']],['footerStyle','Footer',['dark','light']]].map(([k,l,o]:any)=><label key={k} className="flex justify-between items-center py-3 border-b border-soft text-sm">{l}<select value={t[k]||o[0]} onChange={e=>ch(k,e.target.value)} className="bg-transparent border-b border-sage">{o.map((v:string)=><option key={v}>{v}</option>)}</select></label>)}
    <div className="flex gap-4 mt-6"><button onClick={save} className="btn btn-dark">Save theme</button><button onClick={()=>{set(DEFAULT_THEME);applyTheme(DEFAULT_THEME)}} className="btn btn-line">Reset to VELORA palette</button></div>{msg&&<p role="status" className="mt-4 text-sm">{msg}</p>}</div>}
type F={k:string;l:string;t?:'text'|'number'|'area'|'check'|'date'|'img'|'sel';o?:string[];bucket?:string}
const fld=(d:F,x?:any)=>d.t==='check'?<label key={d.k} className="text-sm"><input type="checkbox" name={d.k} defaultChecked={x&&x[d.k]!==undefined?x[d.k]:true}/> {d.l}</label>
 :d.t==='sel'?<select key={d.k} name={d.k} defaultValue={x?.[d.k]} className={box} aria-label={d.l}>{d.o!.map(o=><option key={o}>{o}</option>)}</select>
 :d.t==='img'?<label key={d.k} className="text-xs text-olive">{d.l}<input type="file" name={d.k} accept="image/*" className="block mt-1"/></label>
 :d.t==='area'?<textarea key={d.k} name={d.k} rows={3} defaultValue={x?.[d.k]??''} placeholder={d.l} aria-label={d.l} className={`${box} md:col-span-2`}/>
 :<input key={d.k} name={d.k} step="any" type={d.t==='number'?'number':d.t==='date'?'date':'text'} defaultValue={d.t==='date'?x?.[d.k]?.slice(0,10):x?.[d.k]??''} placeholder={d.l} aria-label={d.l} className={box}/>
function Crud({table,title,fields,order,readOnly,canAdd=true,canDelete=true}:{table:string;title:string;fields:F[];order:string;readOnly?:boolean;canAdd?:boolean;canDelete?:boolean}){
  const [r,set]=useState<any[]>([]);const [msg,setMsg]=useState('');const load=useCallback(()=>{supabase.from(table).select('*').order(order,{ascending:false}).then(({data})=>set(data||[]))},[table,order]);useEffect(load,[load])
  const save=async(e:React.FormEvent<HTMLFormElement>,x?:any)=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),row:any={...(x||{})}
    try{for(const d of fields){const v=f.get(d.k);if(d.t==='check')row[d.k]=v==='on';else if(d.t==='img'){const fl=v as File;if(fl?.size){if(!fl.type.startsWith('image/'))throw new Error('Choose an image file.');row[d.k]=await upload(d.bucket!,`${Date.now()}.${fl.name.split('.').pop()}`,fl)}}
      else if(d.t==='number')row[d.k]=v===''?null:Number(v);else if(d.t==='date')row[d.k]=v?new Date(String(v)).toISOString():null;else row[d.k]=v===''?null:v}
      const {error}=await supabase.from(table).upsert(row);if(error)throw error;setMsg('Saved.');load();if(!x)form.reset()}catch(er:any){setMsg('Could not save: '+er.message)}}
  const del=async(x:any)=>{if(confirm('Delete this item?')){const {error}=await supabase.from(table).delete().eq('id',x.id);setMsg(error?'Could not delete: '+error.message:'Deleted.');load()}}
  return <div><h1 className="font-serif text-5xl mb-8">{title}</h1>{msg&&<p role="status" className="mb-4 text-sm">{msg}</p>}
    {!readOnly&&canAdd&&<form onSubmit={e=>save(e)} className="grid md:grid-cols-3 gap-x-6 gap-y-4 max-w-4xl mb-10">{fields.map(d=>fld(d))}<button className="btn btn-dark md:col-span-3">Add</button></form>}
    {!r.length&&<p className="text-olive">Nothing here yet.</p>}
    {r.map(x=>readOnly?<p key={x.product_id||x.id} className="py-3 border-b border-soft text-sm">{fields.map(d=>`${d.l}: ${x[d.k]??'-'}`).join(' · ')}</p>:
      <details key={x.id} className="border-b border-soft py-3"><summary className="cursor-pointer text-sm">{fields.slice(0,3).map(d=>x[d.k]).filter(v=>v!=null&&typeof v!=='boolean').join(' · ')||x.id}</summary>
        <form onSubmit={e=>save(e,x)} className="grid md:grid-cols-3 gap-x-6 gap-y-4 max-w-4xl mt-4">{fields.map(d=>fld(d,x))}<button className="btn btn-dark">Save</button>{canDelete&&<button type="button" onClick={()=>del(x)} className="underline text-sm">Delete</button>}</form></details>)}</div>}
function Settings({k,title,fields}:{k:string;title:string;fields:F[]}){const [v,set]=useState<any>(null);const [msg,setMsg]=useState('')
  useEffect(()=>{supabase.from('theme_settings').select('value').eq('key',k).maybeSingle().then(({data})=>set(data?.value||{}))},[k]);if(!v)return <p>Loading…</p>
  const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),n:any={...v};fields.forEach(d=>n[d.k]=d.t==='check'?f.get(d.k)==='on':String(f.get(d.k)||''))
    const {error}=await supabase.from('theme_settings').upsert({key:k,value:n});setMsg(error?'Could not save.':'Saved. Live on the storefront.')}
  return <form onSubmit={save} className="max-w-2xl grid gap-4"><h1 className="font-serif text-5xl mb-4">{title}</h1>{fields.map(d=>fld({...d,t:d.t||'text'},v))}<button className="btn btn-dark">Save</button>{msg&&<p role="status" className="text-sm">{msg}</p>}</form>}
function HomeAdmin(){const [s,set]=useState<any[]>([]);const [drag,setDrag]=useState(-1);const [msg,setMsg]=useState('')
  const load=useCallback(()=>{supabase.from('homepage_sections').select('*').order('position').then(({data})=>set(data||[]))},[]);useEffect(load,[load])
  const drop=async(to:number)=>{if(drag<0||drag===to)return;const n=[...s],[m]=n.splice(drag,1);n.splice(to,0,m);set(n);setDrag(-1);await supabase.from('homepage_sections').upsert(n.map((x,i)=>({...x,position:i})))}
  const save=async(e:React.FormEvent<HTMLFormElement>,x:any)=>{e.preventDefault();const f=new FormData(e.currentTarget),row:any={...x,title:f.get('title'),subtitle:f.get('subtitle'),bg_color:f.get('bg')||null,padding_y:Number(f.get('pad')||96),visible:f.get('vis')==='on'}
    try{const im=f.get('img') as File,vd=f.get('vid') as File;if(im?.size){if(!im.type.startsWith('image/'))throw new Error('Choose an image file.');row.image_url=await upload('campaign-media',`${x.key}/image.${im.name.split('.').pop()}`,im)}
      if(vd?.size){if(vd.type!=='video/mp4')throw new Error('Video must be an MP4.');row.video_url=await upload('campaign-media',`${x.key}/video.mp4`,vd)}
      const {error}=await supabase.from('homepage_sections').upsert(row);if(error)throw error;setMsg('Saved.');load()}catch(er:any){setMsg('Could not save: '+er.message)}}
  return <div><h1 className="font-serif text-5xl mb-2">Homepage sections</h1><p className="text-sm text-olive mb-6">Drag a section up or down to reorder it. Open it to edit.</p>{msg&&<p role="status" className="mb-4 text-sm">{msg}</p>}
    {s.map((x,i)=><div key={x.id} draggable onDragStart={()=>setDrag(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(i)} className="border-b border-soft py-3"><details><summary className="cursor-grab capitalize">{x.visible?'':'(hidden) '}{x.key.replace('_',' ')}</summary>
      <form onSubmit={e=>save(e,x)} className="grid md:grid-cols-2 gap-x-6 gap-y-4 max-w-3xl mt-4"><input name="title" defaultValue={x.title||''} placeholder="Heading" aria-label="Heading" className={box}/><input name="subtitle" defaultValue={x.subtitle||''} placeholder="Subtext" aria-label="Subtext" className={box}/>
        <input name="bg" defaultValue={x.bg_color||''} placeholder="Background color, e.g. #AEC3B0" pattern="#[0-9A-Fa-f]{6}|" aria-label="Background color" className={box}/><input name="pad" type="number" min="0" max="240" defaultValue={x.padding_y} aria-label="Vertical padding in px" className={box}/>
        <label className="text-xs text-olive">Image<input type="file" name="img" accept="image/*" className="block mt-1"/></label><label className="text-xs text-olive">Video MP4<input type="file" name="vid" accept="video/mp4" className="block mt-1"/></label>
        <label className="text-sm"><input type="checkbox" name="vis" defaultChecked={x.visible}/> Visible</label><button className="btn btn-dark">Save section</button></form></details></div>)}</div>}
const BK:Record<string,string>={Hero:'hero-media',Products:'product-images',Categories:'category-images',Campaigns:'campaign-media',Videos:'product-videos'}
function MediaAdmin(){const [m,set]=useState<any[]>([]);const [fo,setFo]=useState('Hero');const [q,setQ]=useState('');const [msg,setMsg]=useState('')
  const load=useCallback(()=>{supabase.from('media_library').select('*').order('created_at',{ascending:false}).then(({data})=>set(data||[]))},[]);useEffect(load,[load])
  const add=async(e:React.ChangeEvent<HTMLInputElement>)=>{const fl=e.target.files?.[0];if(!fl)return;try{const vid=fl.type==='video/mp4';if(!vid&&!fl.type.startsWith('image/'))throw new Error('Images or MP4 only.');const path=`library/${Date.now()}-${fl.name.replace(/[^\w.-]/g,'_')}`
    const url=await upload(BK[fo],path,fl);const {error}=await supabase.from('media_library').insert({folder:fo,bucket:BK[fo],path,name:fl.name,url,kind:vid?'video':'image'});if(error)throw error;setMsg('Uploaded.');load()}catch(er:any){setMsg('Upload failed: '+er.message)}e.target.value=''}
  const del=async(x:any)=>{if(!confirm('Delete this file?'))return;await supabase.storage.from(x.bucket).remove([x.path]);await supabase.from('media_library').delete().eq('id',x.id);load()}
  const ren=async(x:any)=>{const n=prompt('New name',x.name);if(n){await supabase.from('media_library').update({name:n}).eq('id',x.id);load()}}
  const l=m.filter(x=>x.folder===fo&&x.name.toLowerCase().includes(q.toLowerCase()))
  return <div><h1 className="font-serif text-5xl mb-6">Media library</h1><div className="flex flex-wrap gap-4 items-end mb-8">{Object.keys(BK).map(f=><button key={f} onClick={()=>setFo(f)} className={`text-sm ${fo===f?'underline underline-offset-8':'text-olive'}`}>{f}</button>)}<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search files" aria-label="Search files" className={`${box} max-w-48`}/><label className="btn btn-dark cursor-pointer">Upload to {fo}<input type="file" accept="image/*,video/mp4" onChange={add} className="sr-only"/></label></div>{msg&&<p role="status" className="mb-4 text-sm">{msg}</p>}
    {!l.length&&<p className="text-olive">No files in this folder.</p>}<div className="grid grid-cols-2 md:grid-cols-4 gap-4">{l.map(x=><div key={x.id} className="text-xs"><div className="aspect-square bg-soft/50">{x.kind==='video'?<video src={x.url} className="w-full h-full object-cover" muted/>:<img src={x.url} alt={x.name} loading="lazy" className="w-full h-full object-cover"/>}</div><p className="truncate mt-1">{x.name}</p>
      <div className="flex gap-3 mt-1"><button onClick={()=>navigator.clipboard.writeText(x.url).then(()=>setMsg('Link copied. Paste it wherever you need this file.'))}>Copy link</button><button onClick={()=>ren(x)}>Rename</button><button onClick={()=>del(x)}>Delete</button></div></div>)}</div></div>}
const TABS=['Dashboard','Orders','Products','Hero','Homepage','Theme','Categories','Coupons','Inventory','Customers','Media','WhatsApp','Footer','Policies','Search','Animations']
function Panel(t:string){const A=(k:string,l:string):F=>({k,l,t:'check'})
  switch(t){case 'Dashboard':return <Dash/>;case 'Orders':return <Orders/>;case 'Products':return <Products/>;case 'Hero':return <HeroAdmin/>;case 'Homepage':return <HomeAdmin/>;case 'Theme':return <ThemeAdmin/>;case 'Media':return <MediaAdmin/>
  case 'Categories':return <Crud table="categories" title="Categories" order="name" fields={[{k:'name',l:'Name'},{k:'slug',l:'Slug (t-shirts)'},{k:'description',l:'Description',t:'area'},{k:'seo_title',l:'SEO title'},{k:'seo_description',l:'SEO description',t:'area'},{k:'banner_url',l:'Banner image',t:'img',bucket:'category-images'}]}/>
  case 'Coupons':return <Crud table="coupons" title="Coupons" order="code" fields={[{k:'code',l:'Code'},{k:'type',l:'Type',t:'sel',o:['percentage','flat']},{k:'value',l:'Value',t:'number'},{k:'min_purchase',l:'Minimum purchase',t:'number'},{k:'usage_limit',l:'Usage limit',t:'number'},{k:'expires_at',l:'Expiry',t:'date'},A('active','Active')]}/>
  case 'Inventory':return <Crud table="inventory" title="Inventory" order="remaining" readOnly fields={[{k:'name',l:'Product'},{k:'sku',l:'SKU'},{k:'sold',l:'Sold'},{k:'remaining',l:'Remaining'},{k:'low_stock',l:'Low stock'}]}/>
  case 'Customers':return <CustomersAdmin/>
  case 'Footer':return <Settings k="footer" title="Footer" fields={[{k:'links',l:'Company links, one per line: Label|/path',t:'area'},{k:'email',l:'Email'},{k:'phone',l:'Phone'},{k:'socials',l:'Social links, one per line: Instagram|https://…',t:'area'},{k:'policies',l:'Policies, one per line: Label|https://…',t:'area'},{k:'copyright',l:'Copyright text'}]}/>
  case 'WhatsApp':return <Settings k="store" title="WhatsApp" fields={[{k:'whatsapp',l:'Store WhatsApp number with country code, digits only (e.g. 919876543210)'}]}/>
  case 'Policies':return <Settings k="policies" title="Policies" fields={['shipping','returns','privacy','terms'].map(k=>({k,l:k[0].toUpperCase()+k.slice(1)+' policy text',t:'area' as const}))}/>
  case 'Search':return <Settings k="search" title="Search" fields={[{k:'trending',l:'Trending searches, one per line',t:'area'},{k:'suggested',l:'Suggested searches, one per line',t:'area'}]}/>
  default:return <Settings k="animations" title="Animations" fields={[A('hero','Hero animation'),A('reveal','Scroll reveal'),A('productHover','Product hover'),A('parallax','Parallax'),A('pageTransition','Page transition'),A('loader','Loading screen')]}/>}}
const crop34=(f:File)=>new Promise<File>((res,rej)=>{const i=new Image();i.onload=()=>{let w=i.width,h=i.height,sx=0,sy=0;const t=3/4;if(w/h>t){const nw=h*t;sx=(w-nw)/2;w=nw}else{const nh=w/t;sy=(h-nh)/2;h=nh}
  const c=document.createElement('canvas');c.width=Math.min(1600,w);c.height=c.width/t;c.getContext('2d')!.drawImage(i,sx,sy,w,h,0,0,c.width,c.height);c.toBlob(b=>b?res(new File([b],'img.jpg',{type:'image/jpeg'})):rej(new Error('Crop failed')),'image/jpeg',.92)};i.onerror=()=>rej(new Error('Could not read that image.'));i.src=URL.createObjectURL(f)})
function ProductEdit({x,done}:{x:any;done:()=>void}){const [im,set]=useState<any[]>([]);const [msg,setMsg]=useState('');const [mode,setMode]=useState('center');const [pend,setPend]=useState<any>(null)
  const load=useCallback(()=>{supabase.from('product_images').select('*').eq('product_id',x.id).order('position').then(({data})=>{set(data||[]);if(data?.[0])supabase.from('products').update({image_url:data[0].url}).eq('id',x.id).then(()=>{})})},[x.id]);useEffect(load,[load])
  const store=async(p:number,f:File)=>{try{const url=await upload('product-images',`${x.id}/${p}-${Date.now()}`,f);const {error}=await supabase.from('product_images').upsert({product_id:x.id,position:p,label:LABELS[p-1],url},{onConflict:'product_id,position'});if(error)throw error;setMsg('Image saved.');load()}catch(e:any){setMsg(e.message)}}
  const put=async(p:number,fl:File)=>{if(!fl.type.startsWith('image/'))return setMsg('Choose an image file.');if(mode==='manual')return setPend({p,fl});try{await store(p,mode==='center'?await crop34(fl):fl)}catch(e:any){setMsg(e.message)}}
  const rm=async(p:number)=>{if(x.published&&im.length<=4)return setMsg('A published product needs at least 4 images. Replace this one, or unpublish first.');await supabase.from('product_images').delete().eq('product_id',x.id).eq('position',p);load()}
  const swap=async(a:any,b:any)=>{await supabase.from('product_images').update({url:b.url}).eq('id',a.id);await supabase.from('product_images').update({url:a.url}).eq('id',b.id);load()}
  const vid=async(fl?:File)=>{try{let url:string|null=null;if(fl){if(fl.type!=='video/mp4')throw new Error('Video must be an MP4.');url=await upload('product-videos',`${x.id}/video.mp4`,fl)}
    const {error}=await supabase.from('products').update({video_url:url}).eq('id',x.id);if(error)throw error;setMsg(url?'Video saved.':'Video removed.');done()}catch(e:any){setMsg(e.message)}}
  const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget)
    const {error}=await supabase.from('products').update({name:f.get('name'),price:Number(f.get('price')),discount_price:f.get('disc')?Number(f.get('disc')):null,stock:Number(f.get('stock')),sizes:String(f.get('sizes')).split(',').map(s=>s.trim()).filter(Boolean),color:f.get('color'),description:f.get('desc'),category:f.get('cat'),is_featured:f.get('feat')==='on',is_new:f.get('new')==='on',published:f.get('pub')==='on'}).eq('id',x.id)
    setMsg(error?'Could not save: '+error.message:'Saved.');done()}
  return <div className="mt-4 space-y-6"><form onSubmit={save} className="grid md:grid-cols-3 gap-x-6 gap-y-4 max-w-4xl"><input name="name" defaultValue={x.name} required aria-label="Name" className={box}/><input name="price" type="number" defaultValue={x.price} required aria-label="Price" className={box}/><input name="disc" type="number" defaultValue={x.discount_price??''} placeholder="Discount price" aria-label="Discount price" className={box}/>
    <input name="stock" type="number" defaultValue={x.stock} aria-label="Stock" className={box}/><input name="color" defaultValue={x.color} aria-label="Color" className={box}/><select name="cat" defaultValue={x.category} className={box} aria-label="Category">{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select>
    <input name="sizes" defaultValue={(x.sizes||[]).join(',')} aria-label="Sizes" className={`${box} md:col-span-2`}/><label className="text-sm flex gap-4"><span><input type="checkbox" name="feat" defaultChecked={x.is_featured}/> Featured</span><span><input type="checkbox" name="new" defaultChecked={x.is_new}/> New</span><span><input type="checkbox" name="pub" defaultChecked={x.published}/> Published</span></label>
    <textarea name="desc" defaultValue={x.description||''} aria-label="Description" className={`${box} md:col-span-3`}/><button className="btn btn-dark md:col-span-3">Save details</button></form>
    <div><label className="text-sm">New images: <select value={mode} onChange={e=>setMode(e.target.value)} className="bg-transparent border-b border-sage"><option value="center">Auto crop to 3:4</option><option value="manual">Choose crop area</option><option value="none">Keep as is</option></select></label>{pend&&<Cropper file={pend.fl} onDone={f=>{store(pend.p,f);setPend(null)}} onCancel={()=>setPend(null)}/>}<div className="grid grid-cols-3 md:grid-cols-6 gap-3 mt-3">{LABELS.map((l,k)=>{const a=im.find(i=>i.position===k+1),b=im.find(i=>i.position===k);return <div key={l} className="text-xs"><div className="aspect-[3/4] bg-soft/50">{a&&<img src={a.url} alt={l} loading="lazy" className="w-full h-full object-cover"/>}</div><p className="mt-1">{k+1}. {l}</p>
      <div className="flex gap-2">{a&&b&&<button type="button" onClick={()=>swap(a,b)}>◀ Swap</button>}{a&&<button type="button" onClick={()=>rm(k+1)}>Remove</button>}</div><label className="underline cursor-pointer">{a?'Replace':'Add'}<input type="file" accept="image/*" className="sr-only" onChange={e=>{const fl=e.target.files?.[0];if(fl)put(k+1,fl);e.target.value=''}}/></label></div>})}</div></div>
    <div className="text-sm">{x.video_url&&<video src={x.video_url} controls className="max-w-xs mb-2"/>}<label className="underline cursor-pointer">{x.video_url?'Replace video (MP4)':'Add video (MP4)'}<input type="file" accept="video/mp4" className="sr-only" onChange={e=>{vid(e.target.files?.[0]);e.target.value=''}}/></label>{x.video_url&&<button type="button" onClick={()=>vid()} className="ml-4 underline">Remove video</button>}</div>{msg&&<p role="status" className="text-sm">{msg}</p>}</div>}
function CustomersAdmin(){const [c,set]=useState<any[]>([]);const [o,setO]=useState<any[]>([]);const [msg,setMsg]=useState('');const [wl,setW]=useState<any[]>([])
  const load=useCallback(()=>{Promise.all([supabase.from('customers').select('*').order('created_at',{ascending:false}),supabase.from('orders').select('*').order('created_at',{ascending:false}),supabase.from('wishlist').select('user_id,product_id,products(name)')]).then(([a,b,w])=>{set(a.data||[]);setO(b.data||[]);setW(w.data||[])})},[]);useEffect(load,[load])
  const st=async(id:string,status:string)=>{const {error}=await supabase.from('customers').update({status}).eq('id',id);setMsg(error?'Could not update.':'Status updated.');load()}
  return <div><h1 className="font-serif text-5xl mb-8">Customers</h1>{msg&&<p role="status" className="mb-4 text-sm">{msg}</p>}{!c.length&&<p className="text-olive">No customers yet. They appear when someone signs up.</p>}
    {c.map(x=>{const mine=o.filter(y=>y.user_id===x.id),spent=mine.filter(y=>y.status!=='cancelled').reduce((s,y)=>s+Number(y.total),0),addr=[...new Set(mine.map(y=>y.shipping_address))]
      return <details key={x.id} className="border-b border-soft py-3"><summary className="cursor-pointer text-sm">{x.full_name||'Customer'} · {mine.length} orders · {inr(spent)} · {x.status}</summary>
        <div className="mt-3 text-sm space-y-2"><p>Phone: {x.phone||'-'} · Joined {new Date(x.created_at).toLocaleDateString()}</p><label>Account status <select value={x.status||'active'} onChange={e=>st(x.id,e.target.value)} className="bg-transparent border-b border-sage"><option>active</option><option>blocked</option></select></label>
          <p className="font-medium">Addresses</p>{addr.length?addr.map(a=><p key={a} className="text-olive">{a}</p>):<p className="text-olive">None yet.</p>}<p className="font-medium">Wishlist</p>{wl.filter(z=>z.user_id===x.id).map(z=><p key={z.product_id} className="text-olive">{z.products?.name}</p>)}<p className="font-medium">Orders</p>{mine.map(y=><p key={y.id}>{y.order_number} · {y.status.replace(/_/g,' ')} · {inr(y.total)}</p>)}</div></details>})}</div>}
function Cropper({file,onDone,onCancel}:{file:File;onDone:(f:File)=>void;onCancel:()=>void}){const W=300,H=400,cv=useRef<HTMLCanvasElement>(null),drag=useRef<any>(null);const [img,setImg]=useState<HTMLImageElement|null>(null);const [z,setZ]=useState(1);const [o,setO]=useState({x:0,y:0})
  useEffect(()=>{const i=new Image();i.onload=()=>setImg(i);i.src=URL.createObjectURL(file)},[file])
  const geo=()=>{const s=Math.max(W/img!.width,H/img!.height)*z,w=img!.width*s,h=img!.height*s;return {w,h,x:Math.min(0,Math.max(W-w,(W-w)/2+o.x)),y:Math.min(0,Math.max(H-h,(H-h)/2+o.y))}}
  useEffect(()=>{if(!img)return;const g=geo(),c=cv.current!.getContext('2d')!;c.clearRect(0,0,W,H);c.drawImage(img,g.x,g.y,g.w,g.h)},[img,z,o])
  const done=()=>{const g=geo(),k=3,c=document.createElement('canvas');c.width=W*k;c.height=H*k;c.getContext('2d')!.drawImage(img!,g.x*k,g.y*k,g.w*k,g.h*k);c.toBlob(b=>b&&onDone(new File([b],'img.jpg',{type:'image/jpeg'})),'image/jpeg',.92)}
  return <div role="dialog" aria-label="Crop image" className="fixed inset-0 z-[120] bg-forest/80 grid place-items-center"><div className="bg-ivory p-6 space-y-4"><p className="text-sm">Drag to position, use the slider to zoom.</p>
    <canvas ref={cv} width={W} height={H} className="touch-none cursor-move bg-soft" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX-o.x,y:e.clientY-o.y}}} onPointerMove={e=>{if(drag.current)setO({x:e.clientX-drag.current.x,y:e.clientY-drag.current.y})}} onPointerUp={()=>{drag.current=null}}/>
    <label className="block text-sm">Zoom<input type="range" min="1" max="3" step="0.05" value={z} onChange={e=>setZ(Number(e.target.value))} className="w-full"/></label><div className="flex gap-3"><button className="btn btn-dark" onClick={done}>Use this crop</button><button className="btn btn-line" onClick={onCancel}>Cancel</button></div></div></div>}
